version: "3.8"

services:
  nodecomp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WIDTH=1920
      - HEIGHT=1080
      - API_URL=https://app.tryiris.dev
    ports:
      - "5900:5900"  # VNC server port
      - "6080:6080"  # Websockify port
    user: "${UID}:${GID}"  # Use the current user's ID and group to avoid permission issues
    command: >
      sh -c "
      chmod -R 777 /iris-data"
    volumes:
      - ${HOME}/.anthropic:/home/computeruse/.anthropic
      - firefox-data:/home/computeruse/.mozilla/firefox-esr
      - ./scripts:/home/computeruse/scripts
      - ./iris-data:/iris-data
    stdin_open: true
    tty: true
    deploy:
      replicas: 1  # This will create 4 instances of mewtwo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  firefox-data:
  rabbitmq-data:
  iris-data:
